name: CI

on:
  push:
    branches: [ main, docs/status-2025-09-05 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Gradle via SDKMAN
        shell: bash
        run: |
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.14.3 || sdk install gradle 8.14.2 || sdk install gradle 8.14.1 || sdk install gradle 8.7
          gradle --version

      - name: Lint (Spotless)
        run: gradle --no-daemon -q lint

      - name: Test
        run: gradle --no-daemon -q test

      - name: Coverage (JaCoCo) and Check
        run: |
          gradle --no-daemon -q jacocoTestReport
          # check includes jacocoTestCoverageVerification (95% thresholds)
          gradle --no-daemon -q check

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test

